//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FanController.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal localize() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FanController.Properties.localize", typeof(localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have official Acer Fan Controller software installed.
        ///Click &quot;Ok&quot; to proceed to download the program or &quot;Cancel&quot; to exit. .
        /// </summary>
        internal static string ACER_PROGRAM {
            get {
                return ResourceManager.GetString("ACER_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        internal static string ATTENTION {
            get {
                return ResourceManager.GetString("ATTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorun with Windows.
        /// </summary>
        internal static string AUTOSTART {
            get {
                return ResourceManager.GetString("AUTOSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Yes&quot; to run the program as administrator or &quot;No&quot; to run default..
        /// </summary>
        internal static string AUTOSTART_ADD {
            get {
                return ResourceManager.GetString("AUTOSTART_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program was added to autorun..
        /// </summary>
        internal static string AUTOSTART_ADDED {
            get {
                return ResourceManager.GetString("AUTOSTART_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program was added to autorun as administrator..
        /// </summary>
        internal static string AUTOSTART_ADDED_ADMIN {
            get {
                return ResourceManager.GetString("AUTOSTART_ADDED_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program was removed from autorun..
        /// </summary>
        internal static string AUTOSTART_REMOVED {
            get {
                return ResourceManager.GetString("AUTOSTART_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        internal static string DEGREE_CELSIUS {
            get {
                return ResourceManager.GetString("DEGREE_CELSIUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program doesn&apos;t have access to fan.dll.
        /// </summary>
        internal static string DLL_NOT_FOUND {
            get {
                return ResourceManager.GetString("DLL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan mode:.
        /// </summary>
        internal static string FAN_MODE {
            get {
                return ResourceManager.GetString("FAN_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected NVIDIA GPU sensor.
        /// </summary>
        internal static string GPU_DETECT {
            get {
                return ResourceManager.GetString("GPU_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N / A.
        /// </summary>
        internal static string INITIALIZATION {
            get {
                return ResourceManager.GetString("INITIALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU:.
        /// </summary>
        internal static string LABEL_CPU {
            get {
                return ResourceManager.GetString("LABEL_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU:.
        /// </summary>
        internal static string LABEL_GPU {
            get {
                return ResourceManager.GetString("LABEL_GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laptop:.
        /// </summary>
        internal static string LAPTOP {
            get {
                return ResourceManager.GetString("LAPTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Mode:.
        /// </summary>
        internal static string MANUAL_MODE {
            get {
                return ResourceManager.GetString("MANUAL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string MAX_MODE {
            get {
                return ResourceManager.GetString("MAX_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting temperature:.
        /// </summary>
        internal static string MAX_MODE_START_TEMP {
            get {
                return ResourceManager.GetString("MAX_MODE_START_TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program has running in tray.
        /// </summary>
        internal static string MINIMIZE {
            get {
                return ResourceManager.GetString("MINIMIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string NORMAL_MODE {
            get {
                return ResourceManager.GetString("NORMAL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalize.
        /// </summary>
        internal static string NORMALIZE {
            get {
                return ResourceManager.GetString("NORMALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this function not available in this version..
        /// </summary>
        internal static string NOT_AVAILABLE_IN_CURRENT_VERSION {
            get {
                return ResourceManager.GetString("NOT_AVAILABLE_IN_CURRENT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get information from sensors GPU and CPU..
        /// </summary>
        internal static string NOT_DETECTED {
            get {
                return ResourceManager.GetString("NOT_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Open Hardware Monitor.
        /// </summary>
        internal static string OHW_DETECT {
            get {
                return ResourceManager.GetString("OHW_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You use old .
        /// </summary>
        internal static string OLD_DLL {
            get {
                return ResourceManager.GetString("OLD_DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program running with admin rules.
        /// </summary>
        internal static string RUN_AS {
            get {
                return ResourceManager.GetString("RUN_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need specify temperature above 40°C and below 99°C.
        /// </summary>
        internal static string SAVE_ERROR_TEXT {
            get {
                return ResourceManager.GetString("SAVE_ERROR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string SAVED {
            get {
                return ResourceManager.GetString("SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You set starting temperature on .
        /// </summary>
        internal static string SAVED_TEXT {
            get {
                return ResourceManager.GetString("SAVED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        internal static string SECONDS {
            get {
                return ResourceManager.GetString("SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string TEMP {
            get {
                return ResourceManager.GetString("TEMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need specify refresh above 1 second and below 99 seconds.
        /// </summary>
        internal static string TICK_TIME_ERROR {
            get {
                return ResourceManager.GetString("TICK_TIME_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update timer.
        /// </summary>
        internal static string TIMER {
            get {
                return ResourceManager.GetString("TIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray.
        /// </summary>
        internal static string TRAY {
            get {
                return ResourceManager.GetString("TRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Т: .
        /// </summary>
        internal static string TRAY_CPU {
            get {
                return ResourceManager.GetString("TRAY_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Т: .
        /// </summary>
        internal static string TRAY_GPU {
            get {
                return ResourceManager.GetString("TRAY_GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode: .
        /// </summary>
        internal static string TRAY_MODE {
            get {
                return ResourceManager.GetString("TRAY_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!.
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You run this program do not on a laptop Acer Aspire 5750G!
        ///On your platform is not guaranteed to work this program.
        ///Use it at your own risk..
        /// </summary>
        internal static string WARNING_TEXT {
            get {
                return ResourceManager.GetString("WARNING_TEXT", resourceCulture);
            }
        }
    }
}
